# freeglaz - open toolkit for the HP DesignJet Z9
# Copyright (C) 2026 The freeglaz contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""FastAPI backend for the freeglaz Print webapp."""
import logging
import logging.handlers
import os
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles

from lib.z9_client import Z9Client, Z9Error

from webapp.backend.routes import charts as charts_routes
from webapp.backend.routes import files as files_routes
from webapp.backend.routes import gamut as gamut_routes
from webapp.backend.routes import jobs as jobs_routes
from webapp.backend.routes import logs as logs_routes
from webapp.backend.routes import papers as papers_routes
from webapp.backend.routes import printers as printers_routes
from webapp.backend.routes import printing as printing_routes
from webapp.backend.routes import profiles as profiles_routes
from webapp.backend.routes import argyll as argyll_routes
from webapp.backend.routes import settings as settings_routes
from webapp.backend.routes import status as status_routes
from webapp.backend.routes import wake as wake_routes
from webapp.backend.services import file_storage
from webapp.backend.services.print_jobs import JobStore
from webapp.backend.services.z9_jobs_subscriber import Z9JobsSubscriber
from webapp.backend.services.z9_status_subscriber import Z9StatusPollSubscriber
from webapp.backend.services.loop_watchdog import LoopWatchdog

# ─── Persistent file logging ────────────────────────────────────────
# The freeglaz backend often runs without an accessible terminal (launched
# via a macOS `.app`, or in the background with `freeglaz web`). Since stdout
# is invisible, we duplicate all logs into a rotating file that the user
# can read with ``tail -f webapp/data/freeglaz.log`` when debugging.
#
# Configuration:
# - Path: ``webapp/data/freeglaz.log`` (consistent with job_mapping.json
#   and job_previews/ which are also in webapp/data/).
# - Rotation: 10 MB max per file, keep 3 backups (~40 MB total).
# - Format: ISO timestamp + level + module + message.

_LOG_DIR = Path(__file__).resolve().parent.parent / "data"
LOG_FILE = _LOG_DIR / "freeglaz.log"


def _configure_file_logging() -> None:
    """Attach a RotatingFileHandler to the root logger.

    Idempotent (uses a marker on the root logger to avoid attaching
    twice if the module is reloaded by uvicorn --reload).
    """
    root = logging.getLogger()
    if getattr(root, "_freeglaz_file_handler_installed", False):
        return
    try:
        _LOG_DIR.mkdir(parents=True, exist_ok=True)
        handler = logging.handlers.RotatingFileHandler(
            LOG_FILE,
            maxBytes=10 * 1024 * 1024,
            backupCount=3,
            encoding="utf-8",
        )
        handler.setLevel(logging.INFO)
        handler.setFormatter(logging.Formatter(
            "%(asctime)s %(levelname)-7s %(name)s — %(message)s",
            datefmt="%Y-%m-%dT%H:%M:%S",
        ))
        root.addHandler(handler)
        root.setLevel(logging.INFO)
        root._freeglaz_file_handler_installed = True  # noqa: SLF001
    except OSError:
        # If we can't write to the folder (permissions, disk full), we
        # don't crash — the app keeps running with just the uvicorn
        # stdout logging.
        logging.getLogger(__name__).warning(
            "Logging fichier %s indisponible, fallback stdout uniquement",
            LOG_FILE,
        )


_configure_file_logging()

# Frontend build folder (generated by `npm run build` in
# webapp/frontend/). If present, the backend serves the bundle; otherwise
# a minimal HTML page explains how to build it.
FRONTEND_DIST = Path(__file__).parent.parent / "frontend" / "dist"

logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Create the shared Z9Client, the capabilities cache, and manage upload storage."""
    logger.info("Starting freeglaz backend")
    # Event-loop watchdog FIRST: if a sync call/deadlock freezes the loop
    # (grey freeze of 10/06 with no trace), it dumps the stacks of all threads.
    app.state.loop_watchdog = LoopWatchdog(_LOG_DIR / "freeglaz_stall.log")
    await app.state.loop_watchdog.start()
    # Z9 ANTI-HAMMERING guard: FREEGLAZ_DISABLE_Z9_SUBSCRIBERS=1 → NO contact with
    # the real Z9 (neither real client, nor subscribers). Set by the conftest → 100%
    # HERMETIC tests (zero request to 192.168.1.50). z9=None also naturally disables the
    # subscribers below. Outside tests: not set → normal behavior.
    if os.getenv("FREEGLAZ_DISABLE_Z9_SUBSCRIBERS") == "1":
        logger.info("FREEGLAZ_DISABLE_Z9_SUBSCRIBERS=1 → Z9 not contacted (hermetic tests)")
        app.state.z9 = None
    else:
        try:
            app.state.z9 = Z9Client.from_env()
            logger.info("Z9Client ready — host=%s", app.state.z9.host)
        except Z9Error as e:
            logger.error("Z9Client not configured: %s", e)
            app.state.z9 = None
    # Argyll CMS availability: resolved ONCE at startup (static per session).
    # NON-BLOCKING — the backend starts regardless; the profiling features simply
    # cannot run until Argyll is installed. Surfaced to the frontend (warning
    # banner) via app.state.argyll and the Status.argyll field.
    from lib.z9_client.argyll import check_argyll
    from webapp.backend.models import ArgyllStatus
    _argyll = check_argyll()
    app.state.argyll = ArgyllStatus(
        ok=_argyll["ok"], bin_ok=_argyll["bin_ok"],
        ref_ok=_argyll["ref_ok"], missing=_argyll["missing"],
        bin_dir=_argyll["bin_dir"], ref_dir=_argyll["ref_dir"],
    )
    if not _argyll["ok"]:
        logger.warning(
            "Argyll CMS incomplete — missing: %s. Profiling features disabled "
            "until fixed. %s",
            ", ".join(_argyll["missing"]), _argyll["install_hint"],
        )
    else:
        logger.info("Argyll CMS available — bin=%s ref=%s",
                    _argyll["bin_dir"], _argyll["ref_dir"])
    app.state.capabilities_cache = {}
    app.state.paper_icc_cache = {}
    app.state.job_store = JobStore()
    app.state.use_mock_print = os.getenv("FREEGLAZ_MOCK_PRINT") == "1"
    if app.state.use_mock_print:
        logger.warning("FREEGLAZ_MOCK_PRINT=1 → mock worker enabled (no send to the Z9)")
    file_storage.cleanup_old(max_age_hours=24)

    # Anti-orphan scan sessions: close any session left active by a previous run.
    # A scan runs in a background thread inside THIS process → a restart kills it,
    # so any non-terminal session on disk is stale by definition (would otherwise
    # block every future scan via the "only one active" lock).
    try:
        from webapp.backend.services import scan_session
        n_orphans = scan_session.cleanup_orphans()
        if n_orphans:
            logger.info("Closed %d orphan scan session(s) at boot", n_orphans)
    except Exception:  # noqa: BLE001 — never block startup on a cleanup failure
        logger.exception("scan session boot cleanup failed")

    # Start the Z9 events subscriber if the Z9 is configured. Must have
    # FINISHED its initial fetch (await start()) before the yield, otherwise
    # the first HTTP requests could get an empty snapshot.
    # (In tests, app.state.z9 is None → subscribers naturally not started.)
    if app.state.z9 is not None:
        sub = Z9StatusPollSubscriber(app.state.z9)
        try:
            await sub.start()
            app.state.z9_status_subscriber = sub
        except Exception:  # noqa: BLE001
            logger.exception("Z9StatusPollSubscriber start failed — SSE disabled")
            app.state.z9_status_subscriber = None
    else:
        app.state.z9_status_subscriber = None

    # Job queue subscriber (Phase 2). Non-blocking: start just launches
    # the task, the first tick happens after poll_interval. The initial
    # snapshot is empty until the 1st successful poll (~3 s) — acceptable
    # for the UI which will briefly show "Chargement...".
    if app.state.z9 is not None:
        jobs_sub = Z9JobsSubscriber(app.state.z9)
        try:
            await jobs_sub.start()
            app.state.z9_jobs_subscriber = jobs_sub
        except Exception:  # noqa: BLE001
            logger.exception("Z9JobsSubscriber start failed — /api/jobs renverra vide")
            app.state.z9_jobs_subscriber = None
    else:
        app.state.z9_jobs_subscriber = None

    yield

    # Shutdown: stop the subscribers BEFORE cancel_all of the jobs (the
    # subscribers don't touch files, but we keep a consistent order
    # — network services first, then local state, then files).
    if app.state.z9_jobs_subscriber is not None:
        await app.state.z9_jobs_subscriber.stop()
    if app.state.z9_status_subscriber is not None:
        await app.state.z9_status_subscriber.stop()
    # We cancel the running jobs BEFORE cleaning up files: the real worker
    # (5b) reads the sources at send time, so the order matters.
    await app.state.job_store.cancel_all()
    file_storage.cleanup_all()
    # Robustness 25/05/2026: cleanly close the keep-alive HTTP sessions
    # (REST + SOAP). Avoids zombie sessions that would retain state
    # (stale queue UUID, TLS cache, cookies) between 2 successive
    # backend startups.
    if app.state.z9 is not None:
        try:
            app.state.z9.close()
            logger.info("Z9Client HTTP sessions closed cleanly")
        except Exception as e:  # noqa: BLE001
            logger.warning("Z9Client close failed: %s", e)
    if getattr(app.state, "loop_watchdog", None) is not None:
        await app.state.loop_watchdog.stop()
    logger.info("Stopping freeglaz backend")


app = FastAPI(title="freeglaz Print", version="0.1.0", lifespan=lifespan)
app.include_router(status_routes.router)
app.include_router(files_routes.router)
app.include_router(printing_routes.router)
app.include_router(jobs_routes.router)
app.include_router(wake_routes.router)
app.include_router(papers_routes.router)
app.include_router(printers_routes.router)
app.include_router(logs_routes.router)
app.include_router(profiles_routes.router)
app.include_router(settings_routes.router)
app.include_router(argyll_routes.router)
app.include_router(gamut_routes.router)
app.include_router(charts_routes.router)


@app.get("/api/health")
async def health(request: Request) -> dict:
    """Trivial endpoint to check that the backend is running. Also carries the
    Argyll availability (static per session) for monitoring / diagnostics."""
    argyll = getattr(request.app.state, "argyll", None)
    return {"ok": True, "argyll": argyll.model_dump() if argyll else None}


# ═════════════════════════════════════════════════════════════════════════
# Serving the built frontend
#
# Must be declared AFTER all the API app.include_router(...) and app.get(...)
# — FastAPI matches routes in registration order, so the SPA catch-all
# must not mask the /api/* routes.
# ═════════════════════════════════════════════════════════════════════════

if (FRONTEND_DIST / "index.html").exists():
    # Vite emits the bundles into dist/assets/ (.js/.css chunks with hash).
    # We mount this subfolder as StaticFiles: correct Content-Type, browser
    # ETag, no passing through the SPA catch-all for these files.
    assets_dir = FRONTEND_DIST / "assets"
    if assets_dir.exists():
        app.mount(
            "/assets",
            StaticFiles(directory=assets_dir),
            name="frontend-assets",
        )

    # Static easter-egg page (self-contained, loaded in an isolated iframe).
    # Vite copies public/easter/ → dist/easter/. Without this dedicated mount
    # the request would fall through to the SPA catch-all below → index.html
    # (the app loading itself inside the egg iframe). Mounted before the
    # catch-all so it takes precedence.
    easter_dir = FRONTEND_DIST / "easter"
    if easter_dir.exists():
        app.mount(
            "/easter",
            StaticFiles(directory=easter_dir),
            name="easter",
        )

    # SPA fallback: any non-API GET route → index.html. The frontend app
    # is single-page with no router (cf. CLAUDE.md), but this fallback
    # leaves room for a future React Router without a backend refactor.
    @app.get("/{full_path:path}", include_in_schema=False)
    async def serve_spa(full_path: str):
        # Guard: /api/* is declared BEFORE this catch-all, should not
        # arrive here. But in case of a mismatch (typo in the client path
        # for example), we return 404 rather than index.html — otherwise
        # a "GET /api/typo" would give 200 HTML, which would mask the bug.
        if full_path == "api" or full_path.startswith("api/"):
            raise HTTPException(status_code=404)
        return FileResponse(FRONTEND_DIST / "index.html")

else:
    @app.get("/", include_in_schema=False, response_class=HTMLResponse)
    async def no_frontend_built():
        """Minimal home page when the frontend has not been built.

        Does not mask the /api/* routes (declared before), so the backend
        stays fully usable via curl/scripts during install.
        """
        return (
            "<!DOCTYPE html>"
            "<html><head><meta charset='utf-8'><title>freeglaz Print</title></head>"
            "<body style='font-family:system-ui;max-width:680px;margin:60px auto;padding:0 20px;color:#222'>"
            "<h1>freeglaz Print — backend OK ✓</h1>"
            "<p>The frontend is not built yet. To generate it:</p>"
            "<pre style='background:#f4f4f6;padding:12px;border-radius:6px'>freeglaz web --build</pre>"
            "<p>Or in development mode (hot reload):</p>"
            "<pre style='background:#f4f4f6;padding:12px;border-radius:6px'>cd webapp/frontend &amp;&amp; npm run dev</pre>"
            "<p style='color:#666;font-size:13px;margin-top:30px'>"
            "The backend itself responds normally on "
            "<code>/api/health</code>, <code>/api/status</code>, etc."
            "</p>"
            "</body></html>"
        )


def _check_port_available(host: str, port: int) -> Optional[str]:
    """Check whether ``host:port`` is free. Return None if OK, otherwise an
    explicit error message to show to the user.

    Robustness 25/05/2026: an old freeglaz process running in the
    background pollutes debugging (frontend requests hit the wrong
    instance, stale queue UUID, etc.). We refuse to start rather than
    letting uvicorn raise an opaque error.
    """
    import socket
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(0.5)
    try:
        # connect_ex returns 0 if something accepts the connection,
        # an errno (typically 61 = Connection refused) if nothing is listening.
        result = s.connect_ex((host if host != "0.0.0.0" else "127.0.0.1", port))
    finally:
        s.close()
    if result != 0:
        return None  # port free, OK
    return (
        f"Port {port} already in use on {host}.\n"
        f"  An old freeglaz process is probably running in the background.\n"
        f"  To kill it:\n"
        f"    lsof -ti :{port} | xargs kill -9\n"
        f"  Or start on another port:\n"
        f"    FREEGLAZ_PORT={port + 1} ./freeglaz web"
    )


def is_up(host: str = "127.0.0.1", port: int = 8765, timeout: float = 0.8) -> bool:
    """True if a freeglaz backend already responds on ``/api/health``.

    Used for the "server already running" case (reuse rather than restart)
    of ``freeglaz open``. Stdlib only (urllib) → portable, no dependency.
    """
    import json as _json
    import urllib.request

    h = "127.0.0.1" if host == "0.0.0.0" else host
    url = f"http://{h}:{port}/api/health"
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:  # noqa: S310
            return bool(_json.loads(r.read().decode("utf-8")).get("ok"))
    except Exception:  # noqa: BLE001 — any network error = no server
        return False


def run_background(host: str = "127.0.0.1", port: int = 8765):
    """Start uvicorn in a daemon thread; return ``(server, thread)``.

    For callers that must CONTINUE after startup (e.g.
    ``freeglaz open``: poll health → upload → open the browser → keep the
    server in the foreground). Unlike ``run()`` which blocks.

    The uvicorn signal handlers are disabled: we're not running in the
    main thread (they would crash with "signal only works in main thread").
    Ctrl+C is handled by the caller via ``server.should_exit``.

    Raises ``RuntimeError`` if the port is already occupied (guard: we only
    call this helper after a negative ``is_up()``, so a port taken here = another
    service, not our backend).
    """
    import threading

    import uvicorn

    msg = _check_port_available(host, port)
    if msg:
        raise RuntimeError(msg)
    config = uvicorn.Config(app, host=host, port=port, log_level="info")
    server = uvicorn.Server(config)
    server.install_signal_handlers = lambda: None  # not the main thread
    thread = threading.Thread(target=server.run, name="freeglaz-uvicorn", daemon=True)
    thread.start()
    return server, thread


def wait_until_up(host: str = "127.0.0.1", port: int = 8765,
                  timeout: float = 20.0, interval: float = 0.4) -> bool:
    """Poll ``/api/health`` until an OK response or ``timeout``. True if up."""
    import time

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if is_up(host, port):
            return True
        time.sleep(interval)
    return is_up(host, port)


def run(host: str = "127.0.0.1", port: int = 8765, reload: bool = False) -> None:
    """Start uvicorn programmatically (reused by ``freeglaz web``).

    With ``reload=True``, uvicorn reloads the app on every code change
    (useful in dev). Reload mode requires the ``module:app`` string rather
    than the direct ``app`` object, because uvicorn must be able to
    re-import the module.

    Robustness patch 25/05/2026: check the port BEFORE startup. If
    occupied, show an explicit message and exit code 1 rather than
    letting uvicorn raise an opaque error.
    """
    import sys
    import uvicorn

    err = _check_port_available(host, port)
    if err:
        logger.error("Startup refused: %s", err)
        # Also print to stderr for the CLI terminal
        print(f"\n❌ {err}\n", file=sys.stderr)
        sys.exit(1)

    logger.info("freeglaz Print backend started on http://%s:%d", host, port)
    if reload:
        uvicorn.run(
            "webapp.backend.main:app",
            host=host, port=port, reload=True, log_level="info",
        )
    else:
        uvicorn.run(app, host=host, port=port, log_level="info")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    run()
