# freeglaz - open toolkit for the HP DesignJet Z9
# Copyright (C) 2026 The freeglaz contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
PDF/X-4 preflight for freeglaz (pure logic, no console I/O).

Python port of freeglaz-preflight.sh. Checks that a PDF generated by
build_pdfx4() respects the freeglaz convention:
  - PDF version 1.6
  - MediaBox, TrimBox present and identical
  - No CropBox/BleedBox (Affinity behavior)
  - XMP Metadata present
  - OutputIntent /GTS_PDFX with DestOutputProfile
  - Image 16 bpc, ICCBased, FlateDecode
  - Image ICC identical to the OutputIntent ICC (APPE transparent — no
    conversion between two embedded profiles; device passthrough further
    requires that embedded profile == the loaded slot's resident)

Usage:
    from .preflight import preflight_pdfx4, Z9PreflightError

    report = preflight_pdfx4("sortie.pdf")
    if not report.ok:
        for c in report.failures():
            print(c.label, c.value)
        raise Z9PreflightError("PDF not compliant", report=report)

The caller (CLI or GUI) decides how to display the report.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

import pikepdf
from pikepdf import Name, Array


# ──────────────────────────────────────────────────────────────────────
# Report structure
# ──────────────────────────────────────────────────────────────────────

@dataclass
class PreflightCheck:
    """An individual preflight check."""
    label: str           # e.g. "Version PDF"
    passed: bool         # True if OK
    value: str = ""      # observed value (for display)
    expected: str = ""   # expected value if different
    warning: bool = False  # non-blocking check (e.g. CropBox present)

    @property
    def icon(self) -> str:
        if self.warning:
            return "⚠"
        return "✓" if self.passed else "✗"

    def __str__(self) -> str:
        parts = [self.label]
        if self.value:
            parts.append(f": {self.value}")
        if self.expected and not self.passed:
            parts.append(f"  (expected: {self.expected})")
        return f"{self.icon} {' '.join(parts).strip()}"


@dataclass
class PreflightReport:
    """Full preflight result."""
    pdf_path: Path
    checks: List[PreflightCheck] = field(default_factory=list)
    fatal_error: Optional[str] = None  # e.g. unreadable PDF

    @property
    def ok(self) -> bool:
        """True if all blocking checks passed."""
        if self.fatal_error:
            return False
        return all(c.passed or c.warning for c in self.checks)

    def failures(self) -> List[PreflightCheck]:
        """List of failed checks (excluding warnings)."""
        return [c for c in self.checks if not c.passed and not c.warning]

    def warnings(self) -> List[PreflightCheck]:
        """List of warnings (CropBox/BleedBox present)."""
        return [c for c in self.checks if c.warning]


# ──────────────────────────────────────────────────────────────────────
# Main preflight
# ──────────────────────────────────────────────────────────────────────

def preflight_pdfx4(pdf_path) -> PreflightReport:
    """
    Check that a PDF respects the freeglaz PDF/X-4 convention.

    Does NOT raise an exception on non-conformance — returns a
    structured report. The caller decides what to do with it (log, raise, ignore
    depending on its warnings, etc.).

    :param pdf_path: path to the PDF to check (str or Path)
    :return: PreflightReport
    """
    pdf_path = Path(pdf_path)
    report = PreflightReport(pdf_path=pdf_path)

    if not pdf_path.exists():
        report.fatal_error = f"File not found: {pdf_path}"
        return report

    try:
        pdf = pikepdf.open(pdf_path)
    except Exception as e:
        report.fatal_error = f"Unable to open the PDF: {e}"
        return report

    try:
        _run_checks(pdf, report)
    finally:
        pdf.close()

    return report


def _run_checks(pdf, report: PreflightReport) -> None:
    """Run the battery of checks on an open PDF."""

    def add(label, passed, value="", expected="", warning=False):
        report.checks.append(PreflightCheck(
            label=label, passed=passed, value=value,
            expected=expected, warning=warning,
        ))

    # ── PDF version ──────────────────────────────────────────────
    version = pdf.pdf_version
    add("Version PDF", version == "1.6", value=version, expected="1.6")

    # ── Page 1 ───────────────────────────────────────────────────
    page = pdf.pages[0]
    p = page.obj
    root = pdf.Root

    # ── Boxes ────────────────────────────────────────────────────
    mb = p.get("/MediaBox")
    tb = p.get("/TrimBox")
    cb = p.get("/CropBox")
    bb = p.get("/BleedBox")

    add("MediaBox present", mb is not None)

    if tb is not None and mb is not None and list(mb) == list(tb):
        add("TrimBox = MediaBox", True, value="OK")
    else:
        add("TrimBox = MediaBox", False, value="DIFF")

    add(
        "CropBox absent (editor-agnostic behavior)",
        cb is None,
        value="absent" if cb is None else f"present {cb}",
        warning=(cb is not None),
    )
    add(
        "BleedBox absent (editor-agnostic behavior)",
        bb is None,
        value="absent" if bb is None else f"present {bb}",
        warning=(bb is not None),
    )

    # ── XMP metadata ──────────────────────────────────────────────
    has_meta = "/Metadata" in root
    add("XMP Metadata present", has_meta)

    # ── OutputIntent ─────────────────────────────────────────────
    oi_list = root.get("/OutputIntents", [])
    has_oi = len(oi_list) >= 1
    add("OutputIntent present", has_oi)

    has_profile = False
    icc_out_bytes = None
    if has_oi:
        oi = oi_list[0]
        s_val = str(oi.get("/S", ""))
        add(
            "OutputIntent /S = /GTS_PDFX",
            s_val == "/GTS_PDFX",
            value=s_val, expected="/GTS_PDFX",
        )
        has_profile = "/DestOutputProfile" in oi
        add("DestOutputProfile present", has_profile)

        oci = str(oi.get("/OutputConditionIdentifier", "")).strip()
        add(
            "OCI not empty",
            bool(oci),
            value=oci if oci else "(empty)",
            warning=not bool(oci),
        )

        if has_profile:
            try:
                icc_out_bytes = bytes(oi["/DestOutputProfile"].read_bytes())
            except Exception as e:
                add("Lecture ICC OutputIntent", False, value=str(e))

    # ── Image ────────────────────────────────────────────────────
    xobjs = p.get("/Resources", {}).get("/XObject", {})
    images = [
        (n, o) for n, o in xobjs.items()
        if o.get("/Subtype") == Name("/Image")
    ]
    add("Image present", len(images) >= 1, value=f"{len(images)} image(s)")

    if images:
        img_name, img = images[0]

        bpc = int(img.get("/BitsPerComponent", 0))
        add("16 bits per component", bpc == 16, value=str(bpc), expected="16")

        cs = img.get("/ColorSpace")
        is_iccbased = (
            isinstance(cs, Array)
            and len(cs) >= 1
            and str(cs[0]) == "/ICCBased"
        )
        add(
            "ColorSpace ICCBased",
            is_iccbased,
            value=str(cs[0]) if isinstance(cs, Array) else str(cs),
        )

        flt = str(img.get("/Filter", ""))
        add(
            "Compression FlateDecode",
            flt == "/FlateDecode",
            value=flt, expected="/FlateDecode",
        )

        # Image ICC = OutputIntent ICC -> APPE transparent (valid guard: the
        # APPE won't convert between two different embedded profiles). This alone
        # does NOT imply device passthrough — that needs the embedded profile to
        # be the loaded slot's resident (the firmware decodes device->ink via it).
        if is_iccbased and icc_out_bytes is not None:
            try:
                icc_img_bytes = bytes(cs[1].read_bytes())
                same = icc_img_bytes == icc_out_bytes
                add(
                    "ICC image = ICC OutputIntent (APPE transparent)",
                    same,
                    value="identical" if same else "DIFFERENT!",
                )
            except Exception as e:
                add("Comparaison ICC image vs OI", False, value=str(e))


# ──────────────────────────────────────────────────────────────────────
# Helper for CLI usage (human formatting)
# ──────────────────────────────────────────────────────────────────────

def format_report(report: PreflightReport, use_color: bool = True) -> str:
    """
    Format a PreflightReport for console display.

    Pure formatting function (no direct I/O). The caller print()s the return.

    :param report: PreflightReport to format
    :param use_color: use ANSI codes
    :return: multi-line string
    """
    if use_color:
        GREEN = "\033[32m"
        RED = "\033[31m"
        YELLOW = "\033[33m"
        BOLD = "\033[1m"
        RESET = "\033[0m"
    else:
        GREEN = RED = YELLOW = BOLD = RESET = ""

    lines = []
    lines.append(f"{BOLD}Preflight freeglaz: {report.pdf_path.name}{RESET}")
    lines.append("")

    if report.fatal_error:
        lines.append(f"   {RED}✗ {report.fatal_error}{RESET}")
        return "\n".join(lines)

    for c in report.checks:
        if c.warning:
            color = YELLOW
        elif c.passed:
            color = GREEN
        else:
            color = RED
        line = f"   {color}{c.icon}{RESET} {BOLD}{c.label}{RESET}"
        if c.value:
            line += f" : {c.value}"
        if c.expected and not c.passed:
            line += f"  (expected: {c.expected})"
        lines.append(line)

    lines.append("")
    if report.ok:
        lines.append(f"   {GREEN}{BOLD}✓ freeglaz-compliant — ready for APPE + Z9{RESET}")
    else:
        failed = len(report.failures())
        lines.append(f"   {RED}{BOLD}✗ {failed} check(s) failed — fix before sending{RESET}")

    return "\n".join(lines)
