"""Tests for profile-compare — backend module `lib/z9_client/profile_compare`.

Covers:
- compare_profiles: dict structure, meta, ICC identity, gamut, WP/BP
- LUT summary: grid_size + Lab ranges for mft2; None for unsupported types
- Curvature: ALWAYS tagged `experimental=True` when requested,
  ABSENT when `with_curvature=False`
- profcheck: absent when no ti3
- profile_curvature: load_a2b_clut, curvature_field, stats_core, order_label

Fixtures: two SYNTHETIC non-HP printer profiles (RGB/Lab, LUT mft2 A2B0,
desc mluc) generated by `fixtures/generate_synthetic_icc.py` — `_RES_A` (grid 9)
and `_RES_B` (grid 11) have DISTINCT LUTs, whitepoints and sizes (required by
the distinction test). The bundled sRGB profiles (`lib/z9_client/assets/`)
serve as neutral secondary profiles.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from lib.z9_client.profile_compare import (
    CURVATURE_EXPERIMENTAL_NOTICE,
    compare_profiles,
)
from lib.z9_client import profile_curvature as curv


ASSETS = Path(__file__).resolve().parents[3] / "lib" / "z9_client" / "assets"
_FIXTURES = Path(__file__).resolve().parent / "fixtures"
_RES_A = _FIXTURES / "synthetic_test_resident_A.icc"
_RES_B = _FIXTURES / "synthetic_test_resident_B.icc"


def _asset(name: str) -> Path:
    p = ASSETS / name
    if not p.exists():
        pytest.skip(f"asset manquant: {name}")
    return p


# ─── compare_profiles: structure & meta ──────────────────────────────


def test_compare_profiles_returns_expected_keys():
    out = compare_profiles([
        _RES_A,
        _RES_B,
    ])
    assert set(out.keys()) >= {"profiles", "meta"}
    assert out["meta"]["n_profiles"] == 2
    assert out["meta"]["with_curvature"] is False
    assert out["meta"]["with_profcheck"] is False
    assert "curvature_notice" not in out  # absent iff flag off
    assert len(out["profiles"]) == 2


# ─── ANTI-REGRESSION: distinction of colorimetric contents ──────
#
# Bug reported on 31/05/2026 (false positive): 3 mirror Z9 profiles
# showed identical metrics in the compare modal. True
# cause: these 3 profiles share byte-for-byte the A2B0/B2A0/wtpt tags
# (only `desc` differs) → identical colorimetric content = same
# metrics (correct by construction).
#
# Guardrail: these tests prove that:
# 1) two profiles REALLY distinct in content (A vs B, different LUTs and
#    grids) give distinct metrics + distinct signatures
#    (the backend never "clones" between profiles);
# 2) the content signature does reflect the colorimetric content
#    (twice the same path → twice the same signature);
# 3) the duplicate group is correctly detected when it exists.


def test_compare_profiles_distinct_content_yields_distinct_metrics():
    """Two profiles distinct in content must give distinct
    metrics — this is the basic contract of the comparison.
    Bug 31/05: slipped through because no test
    verified the DISTINCTION between profiles."""
    out = compare_profiles([
        _RES_A,
        _RES_B,
    ])
    e0, e1 = out["profiles"]
    # distinct file_size (sanity check of input data)
    assert e0["file_size"] != e1["file_size"]
    # Distinct content signatures (proof that the LUT differs)
    assert e0["content_signature"]
    assert e1["content_signature"]
    assert e0["content_signature"] != e1["content_signature"]
    # Distinct WP Lab (at least one component differs)
    assert e0["whitepoint_lab"] != e1["whitepoint_lab"]
    # Distinct gamut volumes (at least one of the intents)
    g0 = e0["gamut"]
    g1 = e1["gamut"]
    if g0.get("status") == "ok" and g1.get("status") == "ok":
        assert g0.get("relative") != g1.get("relative")
    # And no duplicate group
    assert out["meta"]["has_duplicates"] is False
    assert out["meta"]["duplicate_signature_groups"] == []


def test_compare_profiles_identical_content_signals_duplicates():
    """Twice the same profile → same metrics (expected, not a
    bug) AND identical signature AND duplicate group reported."""
    path = _RES_A
    out = compare_profiles([path, path])
    e0, e1 = out["profiles"]
    # Same file → same scalar values (sanity)
    assert e0["file_size"] == e1["file_size"]
    assert e0["content_signature"] == e1["content_signature"]
    assert e0["whitepoint_lab"] == e1["whitepoint_lab"]
    # Duplicate detected and exposed for the UI
    assert out["meta"]["has_duplicates"] is True
    groups = out["meta"]["duplicate_signature_groups"]
    assert len(groups) == 1
    assert groups[0]["n_profiles"] == 2
    assert groups[0]["profile_indices"] == [0, 1]
    assert groups[0]["signature"] == e0["content_signature"]


def test_compare_profiles_content_signature_is_md5_hex16():
    """Expected form: 16 hex characters (truncated md5). Stable from one
    call to the next for the same content."""
    out_a = compare_profiles([
        _RES_A,
        _RES_B,
    ])
    out_b = compare_profiles([
        _RES_A,
        _RES_B,
    ])
    for e in out_a["profiles"] + out_b["profiles"]:
        sig = e["content_signature"]
        assert len(sig) == 16
        # Hex only
        int(sig, 16)
    # Deterministic
    assert out_a["profiles"][0]["content_signature"] \
        == out_b["profiles"][0]["content_signature"]
    assert out_a["profiles"][1]["content_signature"] \
        == out_b["profiles"][1]["content_signature"]


def test_compare_profiles_mixed_distinct_and_duplicate():
    """3 entries: twice A + once B. Reports a single
    duplicate group (the two A's) and leaves B isolated."""
    res_a = _RES_A
    res_b = _RES_B
    out = compare_profiles([res_a, res_b, res_a])
    sigs = [e["content_signature"] for e in out["profiles"]]
    assert sigs[0] == sigs[2]
    assert sigs[0] != sigs[1]
    groups = out["meta"]["duplicate_signature_groups"]
    assert len(groups) == 1
    assert sorted(groups[0]["profile_indices"]) == [0, 2]
    assert groups[0]["n_profiles"] == 2
    assert out["meta"]["has_duplicates"] is True


def test_compare_profiles_three_profiles_aligned():
    out = compare_profiles([
        _RES_A,
        _asset("sRGB_lcms_v10.icc"),
        _asset("eciRGB_v2.icc"),
    ])
    assert out["meta"]["n_profiles"] == 3
    assert len(out["profiles"]) == 3


# ─── ICC identity (header, description, type guess) ───────────────────


def test_compare_profiles_extracts_file_metadata():
    out = compare_profiles([_RES_A])
    e = out["profiles"][0]
    assert e["path"].endswith("synthetic_test_resident_A.icc")
    assert e["file_size"] > 0
    # ICC header: version, class, color spaces
    assert e["icc_version"]  # non-empty
    assert e["device_class"]  # "prtr" / "scnr" / etc.
    assert e["color_space"]   # "RGB" expected for print HP RGB
    assert e["pcs"]           # "Lab " or "XYZ "


def test_compare_profiles_description_present_or_empty_string():
    out = compare_profiles([_asset("sRGB_lcms_v10.icc")])
    e = out["profiles"][0]
    # description may be empty for some profiles, but must be str
    assert isinstance(e["description"], str)
    # type_guess is a string (factory/custom/lcms2/argyll/non-hp...)
    assert isinstance(e["profile_type_guess"], str)


# ─── WP / BP in Lab D50 ───────────────────────────────────────────────


def test_compare_profiles_whitepoint_lab_for_hp_factory():
    out = compare_profiles([_RES_A])
    e = out["profiles"][0]
    # HP print profile: must have a wtpt → non-empty Lab WP.
    assert len(e["whitepoint_lab"]) == 3
    L, a, b = e["whitepoint_lab"]
    # Paper WP: L* expected > 90, a/b close to 0 (±10 generous)
    assert L > 80, f"L* WP={L} suspect (<80) pour papier baryté"
    assert abs(a) < 15
    assert abs(b) < 15


# ─── Gamut volumes (reuses InspectOps/GamutAnalyzer) ───────────────


def test_compare_profiles_gamut_present():
    out = compare_profiles([_RES_A])
    e = out["profiles"][0]
    g = e["gamut"]
    assert g.get("status") in ("ok", "deps_missing", "failed", None)
    # If lcms2 available and profile readable: must have the volumes
    if g.get("status") == "ok":
        # At least one of the main intents has a numeric value
        any_volume = any(
            isinstance(g.get(k), (int, float))
            for k in ("relative", "perceptual", "saturation")
        )
        assert any_volume


# ─── LUT summary: mft2 OK, unsupported types → None ────────────────────


def test_compare_profiles_lut_summary_for_hp_factory():
    out = compare_profiles([_RES_A])
    lut = out["profiles"][0]["lut"]
    if lut is None:
        pytest.skip("LUT A2B0 non mft2 sur ce build")
    assert lut["type"] == "mft2"
    assert isinstance(lut["grid_size"], int)
    assert lut["grid_size"] >= 9  # typical grids 17/33 for print
    # Lab ranges: L in [0..100], a/b in ~[-128..127]
    Lmin, Lmax = lut["lab_l_range"]
    amin, amax = lut["lab_a_range"]
    bmin, bmax = lut["lab_b_range"]
    assert 0 <= Lmin <= Lmax <= 100 + 1e-6
    assert -128 <= amin <= amax <= 128
    assert -128 <= bmin <= bmax <= 128


def test_compare_profiles_lut_summary_none_for_unsupported_type():
    """sRGB X-Rite v4 (mAB) → our curvature does not know it, lut=None
    expected without crash. If the asset is actually mft2, the test passes
    too (conditional assertion)."""
    out = compare_profiles([_asset("sRGB_v4_ICC_preference.icc")])
    e = out["profiles"][0]
    # The rest of the dict must be filled even if lut=None
    assert e["icc_version"]
    assert e["color_space"]
    # lut may be None (mAB) OR dict (mft2) — depending on the profile build
    assert e["lut"] is None or e["lut"]["type"] == "mft2"


# ─── Curvature: EXPERIMENTAL badge always present ───────────────────


def test_compare_profiles_no_curvature_by_default():
    out = compare_profiles([_RES_A])
    assert out["profiles"][0]["curvature"] is None
    assert "curvature_notice" not in out


def test_compare_profiles_curvature_always_experimental_badge():
    out = compare_profiles(
        [_RES_A],
        with_curvature=True,
    )
    # Notice present at the root level
    assert out["curvature_notice"] == CURVATURE_EXPERIMENTAL_NOTICE
    assert "EXPERIMENTAL" in out["curvature_notice"]
    # Notice AND flag present in EACH profile block
    c = out["profiles"][0]["curvature"]
    assert c is not None
    assert c["experimental"] is True
    assert "EXPERIMENTAL" in c["notice"]
    assert c["status"] in ("ok", "unavailable")


def test_compare_profiles_curvature_stats_on_hp_factory():
    out = compare_profiles(
        [_RES_A],
        with_curvature=True,
    )
    c = out["profiles"][0]["curvature"]
    if c["status"] != "ok":
        pytest.skip(f"courbure non calculable : {c.get('reason')}")
    # Valid numeric stats
    for k in ("moy", "med", "p95", "max"):
        assert isinstance(c[k], float)
        assert c[k] >= 0, f"{k} négatif suspect : {c[k]}"
    assert c["max"] >= c["p95"] >= c["med"]
    assert c["grid_native"] >= 9
    assert c["weight_l"] == 2.0


def test_compare_profiles_curvature_meta_flag_propagates():
    out = compare_profiles(
        [_RES_A],
        with_curvature=True,
    )
    assert out["meta"]["with_curvature"] is True


# ─── profcheck: absent when no ti3 ──────────────────────────────


def test_compare_profiles_no_profcheck_without_ti3():
    out = compare_profiles([_RES_A])
    assert out["profiles"][0]["profcheck"] is None
    assert out["meta"]["with_profcheck"] is False


def test_compare_profiles_profcheck_missing_ti3_reports_unavailable(tmp_path):
    fake_ti3 = tmp_path / "ghost.ti3"  # does not exist
    out = compare_profiles(
        [_RES_A],
        ti3_paths=[str(fake_ti3)],
    )
    pc = out["profiles"][0]["profcheck"]
    assert pc is not None
    assert pc["status"] == "unavailable"
    assert out["meta"]["with_profcheck"] is True


def test_compare_profiles_ti3_paths_alignment_short_list():
    """If fewer ti3 than profiles, the missing ones are None (no profcheck)."""
    out = compare_profiles(
        [
            _RES_A,
            _RES_B,
        ],
        ti3_paths=[None],  # only the first would be evaluated — here None → skip
    )
    # Neither has profcheck (None for both)
    assert out["profiles"][0]["profcheck"] is None
    assert out["profiles"][1]["profcheck"] is None


# ─── profile_curvature: unit tests of the module ────────────────────


def test_curvature_load_a2b_clut_returns_grids():
    p = _RES_A
    try:
        g, L, a, b = curv.load_a2b_clut(p)
    except ValueError as e:
        pytest.skip(f"A2B0 non mft2 sur cet asset : {e}")
    assert L.shape == (g, g, g)
    assert a.shape == (g, g, g)
    assert b.shape == (g, g, g)
    assert 0 <= float(L.min()) <= float(L.max()) <= 100 + 1e-6


def test_curvature_laplacian_3d_zero_on_constant_field():
    f = np.ones((9, 9, 9)) * 42.0
    lap = curv.laplacian_3d(f)
    # Laplacian of a constant field = 0 (strict interior)
    assert np.allclose(lap[1:-1, 1:-1, 1:-1], 0.0)


def test_curvature_field_returns_nonnegative_3d():
    g = 9
    L = np.linspace(0, 100, g ** 3).reshape(g, g, g)
    a = np.linspace(-50, 50, g ** 3).reshape(g, g, g)
    b = np.linspace(-50, 50, g ** 3).reshape(g, g, g)
    field = curv.curvature_field(L, a, b)
    assert field.shape == (g, g, g)
    assert (field >= 0).all()


def test_curvature_stats_core_keys_and_ordering():
    rng = np.random.default_rng(42)
    field = rng.uniform(0, 10, size=(9, 9, 9))
    st = curv.stats_core(field)
    assert set(st.keys()) == {"moy", "med", "p95", "mx"}
    # mx >= p95 >= med; moy bounded by mx
    assert st["mx"] >= st["p95"]
    assert st["p95"] >= st["med"]
    assert st["moy"] <= st["mx"]


def test_curvature_order_label_canonical_cases():
    assert curv.order_label(255, 128, 0) == "R≥G≥B"
    assert curv.order_label(0, 128, 255) == "B≥G≥R"
    assert curv.order_label(100, 105, 102) == "R=G=B"  # ±12 → near gray
    assert curv.order_label(255, 0, 200) == "mixte"


def test_curvature_analyze_single_returns_consistent_shape():
    p = _RES_A
    try:
        g_native, g_eff, field, stats = curv.analyze_single(p)
    except ValueError as e:
        pytest.skip(f"A2B0 non mft2 sur cet asset : {e}")
    assert field.shape == (g_eff, g_eff, g_eff)
    assert g_native == g_eff  # no resampling requested
    assert {"moy", "med", "p95", "mx"} <= set(stats.keys())


# ─── PCS XYZ: correct decoding of the LUT (LUT Structure regression) ──
#
# Historical bug: load_a2b_clut ALWAYS decoded the A2B0 nodes with the
# Lab formula. For a PCS XYZ (colprof -ax profiles), the nodes encode
# XYZ → aberrant "Lab" ranges (e.g. all-negative b*) and skewed
# curvature. The fix detects the PCS, applies the output curves, decodes
# XYZ then converts to Lab D50. Tested here on a synthetic XYZ mft2.


def _synth_mft2(pcs: bytes) -> bytes:
    import struct as _st
    g, ic, oc, n_in, n_out = 2, 3, 3, 2, 2
    header = bytearray(128)
    header[16:20] = b"RGB "
    header[20:24] = pcs
    header[36:40] = b"acsp"

    mft2 = bytearray()
    mft2 += b"mft2" + b"\x00\x00\x00\x00"
    mft2 += bytes([ic, oc, g, 0])
    for v in (65536, 0, 0, 0, 65536, 0, 0, 0, 65536):
        mft2 += _st.pack(">i", v)
    mft2 += _st.pack(">H", n_in) + _st.pack(">H", n_out)
    for _ in range(ic):
        mft2 += _st.pack(">HH", 0, 65535)
    # CLUT 2x2x2: black at node 0, D50 white at the last node, gray elsewhere.
    white = (31594, 32768, 27031)
    black = (200, 200, 200)
    mid = (16000, 16500, 13500)
    nodes = []
    for r in range(g):
        for gg in range(g):
            for bb in range(g):
                if (r, gg, bb) == (g - 1, g - 1, g - 1):
                    nodes.append(white)
                elif (r, gg, bb) == (0, 0, 0):
                    nodes.append(black)
                else:
                    nodes.append(mid)
    for node in nodes:
        mft2 += _st.pack(">HHH", *node)
    for _ in range(oc):
        mft2 += _st.pack(">HH", 0, 65535)

    tag_table_off = 128
    a2b0_off = tag_table_off + 4 + 12
    tag_table = _st.pack(">I", 1) + b"A2B0" + _st.pack(">II", a2b0_off, len(mft2))
    out = bytes(header) + tag_table + bytes(mft2)
    return out


def test_load_a2b_clut_xyz_pcs_decoded_as_lab(tmp_path):
    p = tmp_path / "synth_xyz.icc"
    p.write_bytes(_synth_mft2(b"XYZ "))
    g, L, a, b = curv.load_a2b_clut(p)
    assert g == 2
    # D50 white (last node) → L*≈100, a*≈0, b*≈0
    assert abs(L[-1, -1, -1] - 100.0) < 0.5
    assert abs(a[-1, -1, -1]) < 1.0
    assert abs(b[-1, -1, -1]) < 1.0
    # Black (node 0) → low L*
    assert L[0, 0, 0] < 20.0
    # Healthy ranges: L in [0..101], a/b in [-128..128] (NOT the all-negative
    # b* of the bug).
    assert 0 <= L.min() <= L.max() <= 101.0
    assert -128 <= a.min() <= a.max() <= 128
    assert -128 <= b.min() <= b.max() <= 128


def test_load_a2b_clut_xyz_vs_lab_branch_differ(tmp_path):
    """Same bytes, different PCS header → different decoding (proof that
    the XYZ branch is indeed taken and not ignored)."""
    raw = bytearray(_synth_mft2(b"XYZ "))
    px = tmp_path / "x.icc"
    px.write_bytes(bytes(raw))
    raw[20:24] = b"Lab "
    pl = tmp_path / "l.icc"
    pl.write_bytes(bytes(raw))
    _, Lx, ax, bx = curv.load_a2b_clut(px)
    _, Ll, al, bl = curv.load_a2b_clut(pl)
    # The XYZ path brings white back to L*100; the Lab path (raw formula on
    # XYZ bytes) does not.
    assert abs(Lx[-1, -1, -1] - 100.0) < 0.5
    assert abs(Ll[-1, -1, -1] - 100.0) > 5.0
